// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "76a7e217-3449-4347-957a-6f9c5811e71b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float batteryVoltage;
float leftCurrent;
float rightCurrent;
int weaponSpeed;
bool disconnectedBool;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(batteryVoltage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(leftCurrent, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(rightCurrent, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(weaponSpeed, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(disconnectedBool, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
